name: PRSetAssigner
on: 
  pull_request:
    types:
      - opened

jobs:
  assignees:
    name: Set assignees
    runs-on: ubuntu-latest
    steps:
      - name: Set assignees
        run: 'curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{ \"assignees\": [\"${{ github.actor }}\"] }" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees'
