name: PRSetMilestones
on: 
  pull_request:
    types:
      - opened

jobs:
  milestones:
    name: Set milestones
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: checkout
        uses: actions/checkout@v2
      - name: Set milestones
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          REPOSITORY: ${{ github.repository }}
        run: |
          cp -r .github/workflows/go .
          cd go/milestones/set
          go run set-milestones.go
